service: s3select-cleverorc-5e-creatures

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource: "arn:aws:s3:::cleverorc/5e/allCreatures5e.json"

functions:
  GetAllCreatures:
    memorySize: 128
    handler: src/shaefer/s3Select.allCreatures
    events:
      - http:
          path: shaefer/allCreatures
          method: get
          cors: true
  GetCreatureByName:
    memorySize: 128
    handler: src/shaefer/5eCreatures.getCreatureByName
    events:
      - http:
          path: shaefer/{name}
          method: get
          cors: true
  GetCreaturesByCR:
    memorySize: 128
    handler: src/shaefer/5eCreatures.getCreatureByCR
    events:
      - http:
          path: shaefer/cr/{range}
          method: get
          cors: true
  GetCreaturesByAbilityScore:
    memorySize: 128
    handler: src/shaefer/5eCreatures.getCreatureByAbilityScore
    events:
      - http:
          path: shaefer/{abilityScore}/{range}
          method: get
          cors: true
  GetCreatures:
    memorySize: 128
    handler: src/shaefer/5eCreatures.creatureSearch
    events:
      - http:
          path: shaefer/creatureSearch
          method: get
          cors: true