service: s3select-cleverorc-5e-creatures

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource: "arn:aws:s3:::cleverorc/5e/allCreatures5e.json"

functions:
  GetAllCreatures:
    memorySize: 128
    handler: src/creatures/5eCreaturesAPI.allCreatures
    events:
      - http:
          path: creatures/allCreatures
          method: get
          cors: true
  GetCreatureByName:
    memorySize: 128
    handler: src/creatures/5eCreaturesAPI.getCreatureByName
    events:
      - http:
          path: creatures/creature/{name}
          method: get
          cors: true
  GetCreaturesByCR:
    memorySize: 128
    handler: src/creatures/5eCreaturesAPI.getCreatureByCR
    events:
      - http:
          path: creatures/cr/{range}
          method: get
          cors: true
  GetCreaturesByAbilityScore:
    memorySize: 128
    handler: src/creatures/5eCreaturesAPI.getCreatureByAbilityScore
    events:
      - http:
          path: creatures/abilityScore/{abilityScore}/{range}
          method: get
          cors: true
  GetCreatures:
    memorySize: 128
    handler: src/creatures/5eCreaturesAPI.creatureSearch
    events:
      - http:
          path: creatures/creatureSearch
          method: get
          cors: true